---
- fail: msg="Installed ansible version {{ ansible_version.full }}, but ansible version > 2.1.1.1 required"
  when: "{{ ansible_version.full | version_compare('2.1.1.1', '<') }}"

- include: bootstrap_user.yml create_user={{ galaxy_tools_create_bootstrap_user }}
  when: galaxy_tools_create_bootstrap_user and (not galaxy_tools_api_key or galaxy_tools_admin_user_preset_api_key)

- include: tools.yml
  when: galaxy_tools_install_tools

- include: workflows.yml
  when: galaxy_tools_install_workflows

- include: bootstrap_user.yml delete_user={{ galaxy_tools_delete_bootstrap_user }}
  when: galaxy_tools_delete_bootstrap_user
