---

- name: Create/invoke script virtualenv
  pip: name={{ item }} virtualenv={{ galaxy_tools_base_dir }}/venv virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - ephemeris==0.4.0  # Pinned version should make sure ephemeris version matches what the role has been tested with

- include: install_tool_list.yml
  with_items: '{{ galaxy_tools_tool_list_files }}'
  loop_control:
    loop_var: tool_list_file
