---

- name: Create/invoke script virtualenv
  pip: name={{ item }} virtualenv={{ galaxy_tools_base_dir }}/venv virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - pyyaml
    - bioblend

- name: Place the tool management script
  copy: src=install_tool_shed_tools.py dest={{ galaxy_tools_base_dir }}/install_tool_shed_tools.py

- include: install_tool_list.yml
  with_items: galaxy_tools_tool_list_files

- name: Remove tool management script
  file: dest={{ galaxy_tools_base_dir }}/install_tool_shed_tools.py state=absent
