---

- name: Create/invoke script virtualenv (Workflows)
  pip:
    name:
      - pyyaml
      - bioblend
    state: present
    virtualenv: "{{ galaxy_tools_base_dir }}/venv"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"

- name: Place the tool management script
  copy: src=install_workflow.py dest={{ galaxy_tools_base_dir }}/install_workflow.py

- name: Copy workflows
  copy: src={{ item }} dest={{ galaxy_tools_base_dir }}/{{ item | basename }}
  with_items:
    - "{{ galaxy_tools_workflows }}"

- name: Install workflows
  command: chdir={{ galaxy_tools_base_dir }} {{ galaxy_tools_base_dir }}/venv/bin/python install_workflow.py -w "{{ item | basename }}" -a {{ galaxy_tools_api_key }} -g {{ galaxy_tools_galaxy_instance_url }}
  with_items:
    - "{{ galaxy_tools_workflows }}"

- name: Remove workflow script
  file: dest={{ galaxy_tools_base_dir }}/install_workflow.py state=absent
